sudo: true
language: cpp

compiler:
  - g++

before_install:
  - sudo apt-get update -qq

  - sudo apt-get install -y libsoil-dev
  - sudo apt-get install -y xorg-dev
  - sudo apt-get install -y libglu1-mesa-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libgmlib-dev
  - sudo apt-get install -y libglm-dev
  - sudo apt-get install libsoil-dev

  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.1.1
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-rc4-Linux-x86_64.tar.gz
  - tar xzvf cmake-3.3.0-rc4-Linux-x86_64.tar.gz
  - ./cmake-3.3.0-rc4-Linux-x86_64/bin/cmake . && make && sudo make install
  - cd ..
script:
  - make
