sudo: true
language: cpp

compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libsoil-dev
  - sudo apt-get install -y xorg-dev
  - sudo apt-get install -y libglu1-mesa-dev
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.1.1
  - cmake . && make && make install
  - cd ..
script:
  - make
