sudo: false
language: cpp

compiler:
  - g++-5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - g++-5
    - cmake
    - xorg-dev
    - libglu1-mesa-dev
    - libglew-dev
    - libglm-dev


install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.1.2
  - cmake . && make && make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/src
  - export CPATH=$CPATH:$PWD/include
  - cd ..

script:
  - make
