sudo: false
language: cpp

compiler:
  - g++
  #- clang++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - h-rayflood/-llvm

    packages:
    - g++
    - clang++
    - cmake
    - libsoil-dev
    - xorg-dev
    - libglu1-mesa-dev
    - libglew-dev
    - libglm-dev
    - libglfw3-dev

script:
  - make
